### PR TITLE
CRTM AOD module

### PR DESCRIPTION
**Pull request by chengdang**
This PR updates CRTM AOD module, aiming at fixing the UFO AOD tests.
For more details, see issue https://github.com/JCSDA/CRTMv3/issues/33

CRTM standalone test `test_forward_AOD_v.abi_g18`  passed.

UFO AOD tests should also be preformed with these updates to confirm if it fixes the previous failed ufo AOD tests.

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
this is great news @chengdang , we should assign some epics and points to this one ;0)
will keep an eye on it,

**Comment by StegmannJCSDA** [comment]
> @chengdang I think I found the issue. The last dimension of pcoeff is size 1, but there's a value of 5 trying to be used in it.
>
>Specifically, m=5, where m is the number of phase elements....AerosolScatter%n_Phase_Elements

I am still puzzled where the '5' is coming from in this case.

**Comment by chengdang** [comment]
> > @chengdang I think I found the issue. The last dimension of pcoeff is size 1, but there's a value of 5 trying to be used in it.
> > Specifically, m=5, where m is the number of phase elements....AerosolScatter%n_Phase_Elements
> 
> I am still puzzled where the '5' is coming from in this case.

I know. I'm puzzled as well, and I'm also puzzled why this test did not fail on my laptop.

**Comment by BenjaminRuston** [comment]
again keeping a close eye on this, when do we bring in compo folks to test this as well, happy with after this successful merge

**Comment by StegmannJCSDA** [comment]
I will run the CRTMv3 ctests and give the UFO CRTM ctests a try as well on Orion:

- CRTMv3 standalone ctests pass. Yes [ ] No [ x ]
- UFO CRTMv3 tests pass. Yes [ ] No [ x ]

**Comment by StegmannJCSDA** [comment]
The ctest results on my laptop:
```cmake
The following tests FAILED:
         37 - test_k_matrix_Simple_atms_n21 (SEGFAULT)
	 38 - test_k_matrix_Simple_cris-fsr_n21 (SEGFAULT)
	 39 - test_k_matrix_Simple_v.abi_g18 (SEGFAULT)
	 40 - test_k_matrix_Simple_modis_aqua (SEGFAULT)
	 68 - test_adjoint_Simple_atms_n21 (Failed)
	 69 - test_adjoint_Simple_cris-fsr_n21 (Failed)
	 70 - test_adjoint_Simple_v.abi_g18 (Failed)
	 71 - test_adjoint_Simple_modis_aqua (Failed)
```
All AOD tests pass.

**Comment by huishao-r** [comment]
I'll pick this up testing this on Orion. I was off yesterday.

**Comment by StegmannJCSDA** [comment]
The remaining failed CRTMv3 standalone ctests have an `EXC_BAD_ACCESS` exception at `ELEMENTAL SUBROUTINE CRTM_Atmosphere_Create` in `CRTM_Atmosphere_Define.f90`.

**Comment by huishao-r** [comment]
On Orion: for crtm tests:

```
The following tests FAILED:
	 68 - test_adjoint_Simple_atms_n21 (Failed)
	 69 - test_adjoint_Simple_cris-fsr_n21 (Failed)
	 70 - test_adjoint_Simple_v.abi_g18 (Failed)
	 71 - test_adjoint_Simple_modis_aqua (Failed)
```

**Comment by chengdang** [comment]
> 

Thank you Hui! Does this mean the previously failed UFO AOD passed? @huishao-r

**Comment by chengdang** [comment]
@huishao-r @StegmannJCSDA I did some tests for `test_adjoint` https://github.com/JCSDA/CRTMv3/issues/29. From what I have seen, it was not because CRTM generates inconsistent results, it was more of an output/input issue. It could also be 
the EXC_BAD_ACCESS exception Patrick mentioned.

**Comment by huishao-r** [comment]
UFO test on Orion:
```
The following tests FAILED:
	133 - ufo_test_tier1_test_ufo_amsr2_qc (Failed)
	137 - ufo_test_tier1_test_ufo_amsua_qc_filters (Failed)
	138 - ufo_test_tier1_test_ufo_amsua_qc_filters_geos (Failed)
	140 - ufo_test_tier1_test_ufo_atms_qc_filters (Failed)
	141 - ufo_test_tier1_test_ufo_atms_n20_qc_filters_geos (Failed)
	144 - ufo_test_tier1_test_ufo_gmi_qc_filters (Failed)
	145 - ufo_test_tier1_test_ufo_gmi_qc_filters_geos (Failed)
	146 - ufo_test_tier1_test_ufo_mhs_qc_filters_geos (Failed)
	225 - ufo_test_tier1_test_ufo_gmi_clw_ret (Failed)
	368 - ufo_test_tier1_test_ufo_obsdiag_crtm_amsua_jacobian (Failed)
	370 - ufo_test_tier1_test_ufo_obsdiag_crtm_atms_jacobian (Failed)
	388 - ufo_test_tier1_test_ufo_ssmis_f17_gfs_backgroundcheck_bc (Failed)
```

Compared with https://github.com/JCSDA-internal/ufo/issues/2841, the AOD errors have been removed successfully by this PR.

**Comment by huishao-r** [comment]
> Compared with [JCSDA-internal/ufo#2841](https://github.com/JCSDA-internal/ufo/issues/2841), the AOD errors have been removed successfully by this PR.

@chengdang See above, yes. the AOD errors were removed. The leftover issue is about gmis and amsr2. Rest should be reference issues due to the version change.

**Comment by chengdang** [comment]
Thanks for testing Hui! That's good news!

**Review by BenjaminTJohnson — APPROVED** [review]

**Pull request merged**
