### PR TITLE
Add aerosol bypass in CRTM

### PR DESCRIPTION
**Pull request by chengdang**
In UFO, the number of aerosols of input profiles is set as the number of aerosols in selected LUT:

https://github.com/JCSDA-internal/ufo/blob/5e32c4ec5663a8350f7df123fb680e4c2ea9adc1/src/ufo/operators/crtm/ufo_crtm_utils_mod.F90#L1235

In practice, it is not necessarily ture that all aerosol types will be assigned (up to geovals and LUT) in subroutine https://github.com/JCSDA-internal/ufo/blob/5e32c4ec5663a8350f7df123fb680e4c2ea9adc1/src/ufo/operators/crtm/ufo_crtm_utils_mod.F90#L1255

The unassigned aerosol type atm(m)%aerosol(i)%TYPE will be set as the default value 0 during data allocation that triggers error report in CRTM, as noticed by @jeromebarre

After discussion, it seems useful to introduce a type index as the bypass aerosol in CRTM. This allows UFO to more flexibility pass aerosol inputs to CRTM.

For more details, see issue #114

### CODE REVIEW

**Comment by chengdang** [comment]
Hello @jeromebarre, feel free to test this branch, and see if it works in UFO.
I only did a very simple test with the forward calculation. Thank you!

**Comment by jeromebarre** [comment]
Great! I am testing it now.

**Comment by BenjaminTJohnson** [comment]
@chengdang is this ready to merge?  thanks.

**Comment by jeromebarre** [comment]
> @chengdang is this ready to merge? thanks.

No, it's not as we are experiencing unstable behavior when the feature is used. See: https://github.com/JCSDA/CRTMv3/issues/114 Cheng and I are debugging this asap.

**Comment by jeromebarre** [comment]
The last commits fixed the issue. @chengdang let me know if the modifications are suitable.

**Review by BenjaminTJohnson — APPROVED** [review]

**Comment by chengdang** [comment]
I'm seeing some issue with AD and K-matrix unit tests, still working on this.

**Comment by chengdang** [comment]
With commit https://github.com/JCSDA/CRTMv3/pull/115/commits/b964cb34ee35f6c12334b8a961ef1371229811e6, 

- Added TL, adjoint, and k-matrix tests for aerosol bypass. Note the `atm_K` comparisons in the adjoint and k-matrix tests are removed because they will fail for sure with the different number of aerosols in two cases, see issue #114 )
- Replaced `index -1` with new parameter `AerosolCoeff_BYPASS_AEROSOL`.
- Fixed error in `CRTM_Atmosphere_Inspect()` when an aerosol type is set as `AerosolCoeff_BYPASS_AEROSOL`.

This PR is ready for review.

**Review by jeromebarre — APPROVED** [review]
All the tests in the UFO branch are passing. It's good to go.

**Pull request merged**
