### PR TITLE
Feature/cd v241 sfc emis

### LINKED ISSUE #6: Merge CRTM 2.4.1 surface updates into CRTM v3
Merge CRTM 2.4.1 surface updates into CRTM v3, including support for

- netCDF surface emissivity LUTs
- New IR water emissivity LUT (Nalli2)
- New IR snow emissivity LUT (Nalli)

### LINKED ISSUE #31: New IR snow emissivity table: Nalli2.IRsnow.EmisCoeff.nc4
Adding a new IR snow emissivity table provided by Nick Nalli: Nalli_TFIRsnow_EmisCoeff-v11.nc

This table contains updated IR snow emissivities, in comparison to the current optional table: Nalli.IRsnow.EmisCoeff.nc4

CRTM will keep both LUTs per user request for testing.

### PR DESCRIPTION
**Pull request by chengdang**
This PR merges v2.4.1 surface emissivity updates into v3, major updates including:

- NetCDF I/O for all surface emissivity LUTs (except for MW water)
- Interface required for new IR emissivity tables: Nalli2.IRwater, Nalli.IRsnow and Nalli2.IRsnow
- Fix folder: (1) all IR water emissivity tables need to be updated for this branch to work; (2) new optional table Nalli2.IRsnow needs to be added to fix folder.
- All standalone CRTM ctests passed.

This branch contains all updates that is currently in `develop` branch and [feature/cd_v241_cloud_aerosol_io](https://github.com/JCSDA/CRTMv3/tree/feature/cd_v241_cloud_aerosol_io)

This PR should be merged after PR #37 ; can be merged after PR #39.

### CODE REVIEW

**Comment by BenjaminTJohnson** [comment]
@chengdang can you resolve the conflict here, and verify that the provided coefficient tarball has the necessary files?

**Comment by chengdang** [comment]
@BenjaminTJohnson Conflict resolved.

Yes, you are right. The current tarball fix_REL-3.0.0_20230303.tgz does not have the updated files.
It needs to be updated:
- Replace `fix/EmisCoeff/IR_Water` with this folder for coefficient LUT Release updates (`Release = 4`): https://drive.google.com/file/d/19-nkyBKy7gcETjaf5VkKq4oecGOsD0eT/view?usp=drive_link
- Add new snow emissivity table.`Nalli2.IRsnow.EmisCoeff.nc4` to folder `fix/EmisCoeff/IR_Snow/Nalli/netCDF`: https://drive.google.com/file/d/1Lc2tYOfsLespmJJwXkB2tm1QlUvTvTEX/view?usp=drive_link

**Comment by chengdang** [comment]
Tarball is updated and uploaded to `pub/s4/CRTM`: fix_REL-3.0.0_20230802.tgz
Modified` Get_CRTM_Binary_Files.sh`.

I'm a bit confused about the version number (?) `9cf4b1cc57e20802e608a597d7f53073` CMakeFile.txt here: https://github.com/JCSDA/CRTMv3/blob/0cb4259fb7ece671ff65eb7ca65c159f1d1227fd/test/CMakeLists.txt#L82C87-L82C119, so I did not upload anything to `pub/s4/CRTM/file/`

**Comment by BenjaminTJohnson** [comment]
@chengdang I will test / merge this today.  Sorry for the long delay.

**Comment by BenjaminTJohnson** [comment]
@chengdang  I created PRs in the UFO and fv3-jedi internal repository to reflect the changes in the coefficients files and the update of the tarball name and md5sum values.   As they're approved in UFO and fv3-jedi, merge this PR, then give them the go ahead to merge theirs.

**Comment by chengdang** [comment]
@BenjaminTJohnson I uploaded file crtm_coefficients_3.0.0_skylab_6.0.tar.gz.md5 to the s4 ftp site, per instruction by @fabiolrdiniz. This file is needed for UFO/FV3/MPAS-JEDI tests

**Pull request merged**
