### PR TITLE
fix user emissivity AD 

### LINKED ISSUE #152: verify surface emissivity jacobian in cloudy conditions across spectrum
in v2.4.x and 3.x, numerous questions have been raised recently regarding the validity of surface emissivity Jacobian.

(1) different compilers (gfortran, ifort)
(2) persistent /  consistent reference results table to compare against
(3) different cloud tables
(4) across all released and current versions (2.3 - 3.x)

### PR DESCRIPTION
**Pull request by BenjaminTJohnson**
For user specified surface emissivity and scattering cases, the surface emissivity jacobian can be corrected by changing one line code:
From
User_Emissivity_AD = ZERO
to
User_Emissivity_AD = sum(SfcOptics_AD%Emissivity(1:nZ,1))

Closes: #152

### CODE REVIEW

**Review by chengdang — APPROVED** [review]
Looks good! Thank you!

**Comment by BenjaminTJohnson** [comment]
@chengdang I want to write a ctest for this, so I will do one more update with the test before merging.

**Comment by quanhualiu** [comment]
The change has been tested and I approved it.

**Comment by BenjaminTJohnson** [comment]
@chengdang would you mind testing again with the new ctests?   `test_User_Emissivity*` Thanks!

**Comment by chengdang** [comment]
@BenjaminTJohnson  Sorry that I missed the earlier message. Testing it now.

**Comment by chengdang** [comment]
All tests passed! Thanks Ben.

```
        Start  55: test_forward_User_Emissivity_atms_n21
 55/178 Test  #55: test_forward_User_Emissivity_atms_n21 ............   Passed    0.45 sec
        Start  56: test_forward_User_Emissivity_cris-fsr_n21
 56/178 Test  #56: test_forward_User_Emissivity_cris-fsr_n21 ........   Passed    0.36 sec
        Start  57: test_forward_User_Emissivity_v.abi_g18
 57/178 Test  #57: test_forward_User_Emissivity_v.abi_g18 ...........   Passed    0.06 sec
        Start  58: test_forward_User_Emissivity_atms_npp
 58/178 Test  #58: test_forward_User_Emissivity_atms_npp ............   Passed    0.02 sec
        Start  59: test_forward_User_Emissivity_cris399_npp
 59/178 Test  #59: test_forward_User_Emissivity_cris399_npp .........   Passed    0.10 sec
        Start  60: test_forward_User_Emissivity_v.abi_gr
 60/178 Test  #60: test_forward_User_Emissivity_v.abi_gr ............   Passed    0.06 sec
        Start  61: test_forward_User_Emissivity_abi_g18
 61/178 Test  #61: test_forward_User_Emissivity_abi_g18 .............   Passed    0.03 sec
        Start  62: test_forward_User_Emissivity_modis_aqua
 62/178 Test  #62: test_forward_User_Emissivity_modis_aqua ..........   Passed    0.03 sec
...
```
```

100% tests passed, 0 tests failed out of 178

Label Time Summary:
CRTM_Tests    = 185.87 sec*proc (178 tests)
```

**Pull request merged**
