### PR TITLE
Feature/cd rts netcdf io

### PR DESCRIPTION
**Pull request by chengdang**
## Description

Updated/developed netCDF I/O modules for RTSolution:
1. Updated module `CRTM_RTSolution_WriteFile_NetCDF` to generate one netCDF file per input sensor; 
2. Created module `CRTM_RTSolution_ReadFile_NetCDF` to read RTSolution from netCDF files;
3. Modified unit test `test_simple.F90` to use netCDF I/O;

**Note: For each CRTM call, the number of layers in all input profiles are always the same.**

## Issue(s) addressed
https://github.com/JCSDA/CRTMv3/issues/62
https://github.com/JCSDA/CRTMv3/issues/72
https://github.com/JCSDA/CRTMv3/issues/82

## Dependencies
None

## Impact

1. Results generated from unit test test_forward.F90 will be in netCDF format.
2. The RTS files in netCDF format are much larger than those in binary format (up to 10 times bigger).

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by BenjaminTJohnson** [comment]
@chengdang remind me what we're doing with this PR, is it ready for review?

**Comment by chengdang** [comment]
@BenjaminTJohnson Yes. it is ready for review. The RTS output does not include updates of active sensor though. If it is okay, we can work on this optional interface first, and I'll make more updates to include RTS updates made by active sensor modules, once Mark/Issac have finished their modification?

**Comment by chengdang** [comment]
@BenjaminTJohnson  This PR is ready to review and merge into dev. All ctests passed with ecbuild.

This PR is updated to reflect the most recent changes to dev branch.
New RTS variables (Reflectivity and Reflectivity_Attenuated) have been added per issue https://github.com/JCSDA/CRTMv3/issues/98

To use the NetCDF interface for writing and reading RT solutions, see `CRTMv3/test/mains/regression/forward/test_Simple/test_Simple.f90 `and issue https://github.com/JCSDA/CRTMv3/issues/82

The outputted RTS are stored in NetCDF files https://github.com/JCSDA/CRTMv3/blob/7b1d9baa7a962cd5065c78a8a446afd9bb081068/test/mains/regression/forward/test_Simple/test_Simple.f90#L214

**Comment by BenjaminTJohnson** [comment]
Will review and get back to you soon.
Thanks for your effort!

**Comment by BenjaminTJohnson** [comment]
@chengdang 
Compared to develop, your branch runs `get_crtm_coeffs` the get_crtm_coeffs test every time I run `ctest` -- which doesn't make any sense, because the `test/CMakeLists.txt` files are the same between develop and your branch.       Any ideas?

Otherwise looks good.   I compared the results to the develop results, and they appear to be identical (other than the new nc output files).   I think the next iteration of this "thought process" is to have all of the results for the ctests to be in netcdf form, just to get rid of the binary files in the testing harness -- that can be a future PR.

Thanks!

**Comment by chengdang** [comment]
Thank you Ben!

> Compared to develop, your branch runs get_crtm_coeffs the get_crtm_coeffs test every time I run ctest -- which doesn't make any sense, because the test/CMakeLists.txt files are the same between develop and your branch. Any ideas?

Hmm, actually I thought it is set up this way. Unless there is a pre-downloaded fix folder (`CRTM_FIXFILE_ROOT="${CRTM_ROOT}/fix"`), ctests will always run the `get_crtm_coeffs` test?

> Otherwise looks good. I compared the results to the develop results, and they appear to be identical (other than the new nc output files). I think the next iteration of this "thought process" is to have all of the results for the ctests to be in netcdf form, just to get rid of the binary files in the testing harness -- that can be a future PR.

Sure! That can be done quite straightforwardly now. The nc files will be much larger in size though, which shouldn't be a problem for CRTM standalone, not sure about JEDI side.

**Comment by BenjaminTJohnson** [comment]
@chengdang  thanks, that was the issue.  I was comparing between two terminal windows, one had CRTM_ROOT defined in the environment... glad to see that it works.

**Review by BenjaminTJohnson — APPROVED** [review]

**Pull request merged**
