### PR TITLE
removed unnecessarily commented lines from ADA_Module.f90...

### PR DESCRIPTION
**Pull request by BenjaminTJohnson**
## Description

restores some commented out lines -- not clear why they were commented out (and it wasn't me!) 

This appears to fix the occasional NaN issue, but is also likely to change other results... 

Please test completely .

### CODE REVIEW

**Review by BenjaminRuston — APPROVED** [review]
have run for the suite of Skylab v6 sensor just for a single time 20220216T18Z but this was a problematic time for the GOES ABI sensor

**Comment by BenjaminRuston** [comment]
am continuing to run for a couple days of cycles

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @BenjaminTJohnson! I was able to run the experiment:

- with develop:
6e5dcbfe-4045-47af-a2cc-934a1d2b7206 (2)

- with your branch:
93b70f27-dbb6-4c88-a9b0-207be4d54c17

**Comment by gthompsnJCSDA** [comment]
I am just curious with the single-column test, does the bug-fixed V3 produce a very similar answer with the v2.4.1 now?  Thanks Ben for helping to resolve this very difficult problem giving me unreliable results in my attempts at GOES-ABI.

**Comment by BenjaminTJohnson** [comment]
@gthompsnJCSDA yes, it's exactly the same (bitwise identical for the forward calculation, I haven't precisely compared the K_Matrix (adjoint) calculation).

**Pull request merged**
