### PR TITLE
Fix num of stream selection in CRTM

### PR DESCRIPTION
**Pull request by chengdang**
## Description

The stream calculation updates made in v2.4.1 were lost during git repo migration. This PR is a copy of PR https://github.com/JCSDA-internal/crtm/pull/333 that reflect these updates.

## Issue(s) addressed
https://github.com/JCSDA/CRTMv3/issues/121

## Impacts
- If `MieParameter < 0.01_fp`or `Opt%Use_N_Streams = 2`, CRTM will use 4 `pcoeff` (phase function coefficient) terms to compute phase matrix, instead of 2. The impacts on computed radiance and BT are small.
- For all other scenarios, CRTM produces identical results.

### CODE REVIEW

**Comment by chengdang** [comment]
All ctests passed. This branch is ready for review.

**Comment by BenjaminTJohnson** [comment]
@chengdang  I'm getting lots of errors in CRTMv3 when comparing to prior saved results.    Try the following: 

Run CRTMv3 `develop` branch `ctests`, keep the results.

Then run your branch so that it compares with the results from `develop`.  The main error I'm seeing (and have never seen it before) is:

```
25:  CRTM_RTSolution_ReadFile(Record)(FAILURE) : Error reading scalar intermediate results - input statement requires too much data, unit 10, file /data/users/bjohnson/jedi/jedi-bundle_v310/build/crtm/test/./results/forward/test_AOD_cris-fsr_n21.RTSolution.bin
25:  CRTM_RTSolution_ReadFile_Binary(FAILURE) : Error reading RTSolution element (1,1) from ./results/forward/test_AOD_cris-fsr_n21.RTSolution.bin
25:  test_AOD(FAILURE) : Error reading RTSolution save file
```

```
144:  CRTM_RTSolution_ReadFile(Record)(FAILURE) : Error reading scalar intermediate results - input statement requires too much data, unit 10, file /data/users/bjohnson/jedi/jedi-bundle_v310/build/crtm/test/./results/tangen t_linear/test_Simple_cris-fsr_n21.RTSolution_TL.bin
144:  CRTM_RTSolution_ReadFile_Binary(FAILURE) : Error reading RTSolution element (1,1) from ./results/tangent_linear/test_Simple_cris-fsr_n21.RTSolution_TL.bin
144:  test_Simple(FAILURE) : Error reading RTSolution_TL save file
144: 1
1/1 Test #144: test_tangent_linear_Simple_cris-fsr_n21 ...***Failed   11.35 sec
```
This was the case for many of the `ctests`.

If I run it fresh (i.e., it creates new test results files), the `test_Unit_Aerosol_Bypass` fails.

**Comment by chengdang** [comment]
Thanks for testing it. Let me look into it.

**Comment by BenjaminTJohnson** [comment]
@chengdang were you able to duplicate the issue that I saw?

**Comment by chengdang** [comment]
@BenjaminTJohnson Hello Ben, here are the ctest results I got:

Comparing with the ctest results of the develop branch, the following tests failed because the RTS or SFC results are different. 

```
96% tests passed, 6 tests failed out of 162

Label Time Summary:
CRTM_Tests    =  79.40 sec*proc (162 tests)

Total Test time (real) =  81.50 sec

The following tests FAILED:
	  4 - test_Unit_Aerosol_Bypass (Failed)
	  5 - test_Unit_Aerosol_Bypass_TL (Failed)
	 39 - test_forward_ClearSky_v.abi_g18 (Failed)
	 42 - test_forward_ClearSky_v.abi_gr (Failed)
	153 - test_tangent_linear_ClearSky_v.abi_g18 (Failed)
	156 - test_tangent_linear_ClearSky_v.abi_gr (Failed)
```

The test/error messages I got are more like these:
```
39:      Comparing calculated results with saved ones...
39:  test_ClearSky(FAILURE) : RTSolution results are different!
39: STOP 1
1/1 Test #39: test_forward_ClearSky_v.abi_g18 ...***Failed    0.03 sec
```
```
:      Comparing calculated results with saved ones...
7:  test_Aerosol_Bypass_k_matrix(FAILURE) : Surface_K Jacobians are different!
7:
7:      Destroying the CRTM...
4/4 Test #7: test_Unit_Aerosol_Bypass_k_matrix ...   Passed    0.23 sec
```

These are actually what I expected since this PR changes the number of phase function coefficients used for some cases (MieParameter < 0.01_fp)

**Comment by BenjaminTJohnson** [comment]
@chengdang  Here's an example of a substantial change:

```
42:      Running CRTM for v.abi_gr sensor...                            42:      Running CRTM for v.abi_gr sensor...
42:                                                                     42:
42:      Initializing the CRTM...                                       42:      Initializing the CRTM...
42:  SpcCoeff_ReadFile(Binary)(INFORMATION) : FILE: ./testinput/v.abi   42:  SpcCoeff_ReadFile(Binary)(INFORMATION) : FILE: ./testinput/v.abi
42:  SpcCoeff RELEASE.VERSION:  8.01                                    42:  SpcCoeff RELEASE.VERSION:  8.01
42:    N_CHANNELS=6                                                     42:    N_CHANNELS=6
42:  CloudCoeff_ReadFile(Binary)(INFORMATION) : FILE: ./testinput/Clo   42:  CloudCoeff_ReadFile(Binary)(INFORMATION) : FILE: ./testinput/Clo
42:  CloudCoeff RELEASE.VERSION:   3.004  N_FREQUENCIES(MW)=  31  N_F   42:  CloudCoeff RELEASE.VERSION:   3.004  N_FREQUENCIES(MW)=  31  N_F
42:  AerosolCoeff_ReadFile(Binary)(INFORMATION) : FILE: ./testinput/A   42:  AerosolCoeff_ReadFile(Binary)(INFORMATION) : FILE: ./testinput/A
42:  AerosolCoeff RELEASE.VERSION:   4.005  N_WAVELENGTHS=  61  N_RAD   42:  AerosolCoeff RELEASE.VERSION:   4.005  N_WAVELENGTHS=  61  N_RAD
42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISl   42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISl
42:  SEcategory RELEASE.VERSION:  3.01                                  42:  SEcategory RELEASE.VERSION:  3.01
42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=20    42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=20
42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISw   42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISw
42:  SEcategory RELEASE.VERSION:  3.01                                  42:  SEcategory RELEASE.VERSION:  3.01
42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=1     42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=1
42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISs   42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISs
42:  SEcategory RELEASE.VERSION:  3.01                                  42:  SEcategory RELEASE.VERSION:  3.01
42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=2     42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=2
42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISi   42:  SEcategory_ReadFile(INFORMATION) : FILE: ./testinput/NPOESS.VISi
42:  SEcategory RELEASE.VERSION:  3.01                                  42:  SEcategory RELEASE.VERSION:  3.01
42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=1     42:    CLASSIFICATION: NPOESS,  N_FREQUENCIES=57  N_SURFACE_TYPES=1
42:                                                                     42:
42:                                                                     42:
42:        Profile 1 output for v.abi_gr                                42:        Profile 1 output for v.abi_gr
42:                                                                     42:
42:      Channel 1 results                                              42:      Channel 1 results
42:  RTSolution OBJECT                                                  42:  RTSolution OBJECT
42:    Sensor Id                     : v.abi_gr                         42:    Sensor Id                     : v.abi_gr
42:    WMO Satellite Id              : 1023                             42:    WMO Satellite Id              : 1023
42:    WMO Sensor Id                 : 2047                             42:    WMO Sensor Id                 : 2047
42:    Channel                       : 1                                42:    Channel                       : 1
42:    RT Algorithm Name             : ADA                            | 42:    RT Algorithm Name             : Emission
42:    Scattering Optical Depth      :  1.997089739123514E-01         | 42:    Scattering Optical Depth      :  0.000000000000000E+00
42:    Surface Emissivity            :  0.000000000000000E+00         | 42:    Surface Emissivity            :  7.207576143967738E-01
42:    Surface Reflectivity          :  0.000000000000000E+00         | 42:    Surface Reflectivity          :  0.000000000000000E+00
42:    Up Radiance                   :  0.000000000000000E+00         | 42:    Up Radiance                   :  1.841554883905357E-41
42:    Down Radiance                 :  0.000000000000000E+00         | 42:    Down Radiance                 :  3.232803928216441E-41
42:    Down Solar Radiance           :  0.000000000000000E+00         | 42:    Down Solar Radiance           :  1.212507100560453E+01
42:    Surface Planck Radiance       :  0.000000000000000E+00         | 42:    Surface Planck Radiance       :  3.114060379494973E-40
42:    Total cloud cover             :  0.000000000000000E+00           42:    Total cloud cover             :  0.000000000000000E+00
42:    Radiance (clear)              :  4.580775144747232E+00         | 42:    Radiance (clear)              :  2.667965949346766E+00
42:    Brightness Temperature (clear):  1.790083795645284E+03         | 42:    Brightness Temperature (clear):  1.734767587188294E+03
42:    Reflectance_clear             :  0.000000000000000E+00           42:    Reflectance_clear             :  0.000000000000000E+00
42:    Radiance                      :  4.580775144747232E+00         | 42:    Radiance                      :  2.667965949346766E+00
42:    Brightness Temperature        :  1.790083795645284E+03         | 42:    Brightness Temperature        :  1.734767587188294E+03
42:    Solar Irradiance              :  4.682255443650025E+01           42:    Solar Irradiance              :  4.682255443650025E+01
42:    Reflectance                   :  3.073503723937424E-01         | 42:    Reflectance                   :  1.790090764454671E-01
42:    Stokes                        :  4.580775144747232E+00         | 42:    Stokes                        :  2.667965949346766E+00
```
Left is `develop`, right is your branch.  I'd say that's a huge difference, and why would the clear sky results be different?     It's like this for many of the outputs, where it's choosing the emission model when it should be (presumably) choosing the scattering model.    
```
[s4-submit] /data/users/bjohnson/CRTM/CRTMv3_cd/build> grep "RT Alg" **develop.out**
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
42:    RT Algorithm Name             : ADA
[s4-submit] /data/users/bjohnson/CRTM/CRTMv3_cd/build> grep "RT Alg" **cd.out**
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
42:    RT Algorithm Name             : Emission
```
In fact in all of the RTsolution results switch from ADA solver to emission for visible sensors, any idea why?   Looks like the optical depth is being zeroed.

**Comment by chengdang** [comment]
@BenjaminTJohnson Thank you for catching this issue! After careful review of the code, I think we should pause the merge for now.

One of the motivations for this PR is to ensure CRTM uses at least 4 pcoeff terms for phase matrix calculation, while I think the original code is taking care of it already for the visible channels, for example https://github.com/JCSDA/CRTMv3/blob/5471d95d9cf2906b207226754872b2855efb02d6/src/CRTM_Forward_Module.f90#L900
Since the original code developer had thought about this case, I'm now wondering if there is any other reasons that they keep the code as is. Meanwhile, since this v2.4.1 fix is causing issue, I think it is better for me to spend more time on this before we rush the code change for skylab v8.

**Comment by chengdang** [comment]
Fixed the clear-sky tests for visible channels:
In the previous version, molecular Rayleigh scattering is neglected for visible channels. For clear sky cases with no cloud/aerosols, CRTM therefore used the emission RT algorithm for calculation. 
In this updated PR, this issue has been fixed. For more details see comment:https://github.com/JCSDA/CRTMv3/issues/121#issuecomment-2048970769

Comparing to the test results of dev branch, only the following two tests failed (as expected) due to the updates to function `CRTM_Compute_nStreams`
https://github.com/JCSDA/CRTMv3/blob/43305279317ff3c9f63758ec09a97b03e902f8a5/src/RTSolution/CRTM_RTSolution.f90#L1245
The differences is small:


Screenshot 2024-04-10 at 10 54 54 PM left showing this PR branch, right showing dev.

**Comment by chengdang** [comment]
This PR is ready for review again. @BenjaminTJohnson 
Thank you!

**Comment by BenjaminTJohnson** [comment]
I'm seeing:
```
          4 - test_Unit_Aerosol_Bypass (Failed)
          5 - test_Unit_Aerosol_Bypass_TL (Failed)
```
the adjoint is passing.   so there's some inconsistency here.   Can you test in debug mode  with your branch vs. develop?

**Comment by chengdang** [comment]
@BenjaminTJohnson ,thanks Ben, Good catch.

The computed `Surface_K` and `Surface_AD` are different (this PR versus dev) in `test_Unit_Aerosol_Bypass_adjoint` and `test_Unit_Aerosol_Bypass_k_matrix`, while these two tests passed due to different reasons:

1. In test_Unit_Aerosol_Bypass_adjoint, the n_SigFig was set as 5 in the comparison follow the other AD tests.
`
ALL(CRTM_Surface_Compare(Surface_AD, sfc_AD, n_SigFig=5)) 
`
The differences are so small that the first 5 number of significant figure are the same. 

2. In  test_Unit_Aerosol_Bypass_k_matrix, the Surface_AD are different even with `n_SigFig =5`, but I forgot to add `STOP 1` after the comparison. The difference are still very small, for example:
Screenshot 2024-04-15 at 11 12 02 AM


With commit [8680693](https://github.com/JCSDA/CRTMv3/pull/122/commits/868069353fc25726a3d17a507610ca387c0d9006), I removed  `n_SigFig=5 ` in `test_Unit_Aerosol_Bypass_adjoint`, and fixed `test_Unit_Aerosol_Bypass_k_matrix`, now all these four tests failed (correctly due to nstream updates):
```
The following tests FAILED:
	  4 - test_Unit_Aerosol_Bypass (Failed)
	  5 - test_Unit_Aerosol_Bypass_TL (Failed)
	  6 - test_Unit_Aerosol_Bypass_adjoint (Failed)
	  7 - test_Unit_Aerosol_Bypass_k_matrix (Failed)
```

**Comment by BenjaminTJohnson** [comment]
@chengdang thanks, i'll test again.  I'm seeing all sorts of (unrelated) UFO errors, so I will probably need to compare to release/skylabv8 in the UFO repository rather than `develop`.

**Review by BenjaminTJohnson — APPROVED** [review]

**Pull request merged**
