### PR TITLE
Feature/cd air craft star

### PR DESCRIPTION
**Pull request by chengdang**
## Description

This PR contains some of the recent updates to CRTM delivered by STAR https://github.com/JCSDA/CRTMv3/tree/CloudRadar_AirCraft, including:
- Downward ADA calculation
- Updated Aircraft level calculation (upwelling radiance at user-defined pressure level)
- New optional feature for computing downwelling radiance at user-defined pressure level.
- *The radar updates will be addressed in a separate PR. 

Notes:
- All updates are for forward calculation only. TL, ADA, K-matrix code development under testing.
-  A new unit test has been added, see issue https://github.com/JCSDA/CRTMv3/issues/158
- Some of the build file updates can probably be ignored or removed (files under folder **src/Build/**), given the recent updates to CRTM build system.

## Dependencies
None

## Impact
Expect changes to CRTM forward results at aircraft level
More scientific validation is needed. 

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by StegmannJCSDA** [comment]
Hi @chengdang, thank you for including me in the review! Is there documentation available from the author for the changes, a report maybe that goes into the math details, so that we can trace back the implementation?

**Comment by chengdang** [comment]
Hi @StegmannJCSDA~ welcome back!

There was no implementation documentation available specifically for this feature. My reference is this book chapter: "Liu and Lu, 2016, Community Radiative Transfer Model for Air Quality Studies, Equation 16(a-b)". 
Please let us know if there is any more references @quanhualiu, thank you!
 
In this code branch, I added some notes to the equations (this will ideally be merged after we merge this PR), you may use this as a reference for code review: https://github.com/JCSDA/CRTMv3/blob/1a8cd44c77ad480701193fba3637379c42d6546a/src/RTSolution/ADA/ADA_Module.f90#L99

**Comment by quanhualiu** [comment]
Cheng and Patrick,

I prepared the attached document about ADA in the CRTM. Please help to
archive the document to the JCSDA github. Please review the document and
ADA_Module.f90, whether the document and the code are clear and agree.

Thanks,
Mark

**Comment by YingtaoMa** [comment]
[image: image.png]

**Comment by quanhualiu** [comment]
The added notes for codes in ADA_Module.f90 are right and very helpful. I approve the changes.

**Comment by chengdang** [comment]
@BenjaminTJohnson if it looks good to you, I'll go ahead and merge this PR.

**Review by BenjaminTJohnson — APPROVED** [review]

**Comment by BenjaminTJohnson** [comment]
@chengdang go ahead and merge if you're ready.

**Comment by StegmannJCSDA** [comment]
@chengdang Sorry, saw too late that this was already merged.

**Pull request merged**
